# Generated by Django 3.2.9 on 2021-11-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Core",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_id",
                    models.CharField(
                        editable=False,
                        max_length=40,
                        unique=True,
                        verbose_name="reuse count",
                    ),
                ),
                (
                    "reuse_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="reuse count"
                    ),
                ),
                (
                    "payload",
                    models.PositiveIntegerField(default=0, verbose_name="payload"),
                ),
            ],
            options={
                "verbose_name": "Core",
                "verbose_name_plural": "Cores",
            },
        ),
    ]
